# Generated by Django 4.0.2 on 2022-02-21 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import obstacles.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obstacle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('-1Error', 'Error'), ('0Pothole', 'Pothole')], default='-1Error', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
            ],
        ),
        migrations.CreateModel(
            name='UserObstacleComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('obstacle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obstacles.obstacle')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserObstacleCommentPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(default='images/default.jpg', upload_to=obstacles.models.get_obstacle_comment_photo_path)),
                ('user_obstacle_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obstacles.userobstaclecomment')),
            ],
        ),
        migrations.CreateModel(
            name='ObstaclePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(default='images/default.jpg', upload_to=obstacles.models.get_obstacle_photo_path)),
                ('obstacle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obstacles.obstacle')),
            ],
        ),
    ]
