# Generated by Django 4.0.2 on 2022-02-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstacles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obstacle',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
