# Generated by Django 4.0.2 on 2022-02-25 21:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('obstacles', '0002_obstacle_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userobstaclecomment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userobstaclecomment',
            name='obstacle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='obstacles.obstacle'),
        ),
    ]
