# Generated by Django 4.0.2 on 2022-02-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstacles', '0003_alter_userobstaclecomment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obstacle',
            name='type',
            field=models.CharField(choices=[('Error', 'Error'), ('Pothole', 'Pothole')], default='Error', max_length=10),
        ),
    ]
