# Generated by Django 4.0.2 on 2022-02-25 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obstacles', '0005_rename_userobstaclecomment_obstaclecomment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obstaclecommentphoto',
            old_name='user_obstacle_comment',
            new_name='obstacle_comment',
        ),
    ]
