# Generated by Django 4.0.2 on 2022-02-25 23:39

from django.db import migrations, models
import django.db.models.deletion
import obstacles.models


class Migration(migrations.Migration):

    dependencies = [
        ('obstacles', '0006_rename_user_obstacle_comment_obstaclecommentphoto_obstacle_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obstaclecommentphoto',
            name='obstacle_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='obstacles.obstaclecomment'),
        ),
        migrations.AlterField(
            model_name='obstaclecommentphoto',
            name='photo',
            field=models.ImageField(default='images/default.jpg', max_length=255, upload_to=obstacles.models.get_obstacle_comment_photo_path),
        ),
    ]
