# Generated by Django 4.0.2 on 2022-02-26 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('obstacles', '0007_alter_obstaclecommentphoto_obstacle_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obstacle',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='obstacle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='obstacle',
            name='location',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
        migrations.AlterField(
            model_name='obstacle',
            name='type',
            field=models.CharField(choices=[('Error', 'Error'), ('Obstacle', 'Obstacle'), ('Pothole', 'Pothole')], default='Obstacle', max_length=10),
        ),
    ]
