# Generated by Django 4.0.2 on 2022-02-26 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('obstacles', '0008_alter_obstacle_author_alter_obstacle_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obstaclecomment',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='obstacle',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
    ]
