# Generated by Django 4.0.2 on 2022-02-26 10:23

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images/default.jpg', upload_to=accounts.models.get_user_avatar_path),
        ),
    ]
