# Generated by Django 4.0.2 on 2022-02-26 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteplace',
            name='last_modified',
        ),
    ]
